### ISSUE TITLE
弹幕消失bug及一些疑问

### ISSUE THREAD

**Issue by junZhangda** [bytedance/danmu.js#13]
弹幕暂停顶部底部弹幕持续时间结束后，弹幕会自动消失。

弹幕时间轴跳转后，只显示跳转时间后的弹幕，不显示弹幕出现时间+持续时间>跳转后时间的弹幕，以后版本是否会支持显示。

以后版本是否会支持弹幕轨道允许重叠显示所有弹幕。

**Comment by gemxx** [comment]
暂无支持计划
