### ISSUE TITLE
为什么同一条弹幕会不停的在循环出现？

### ISSUE THREAD

**Issue by conanjunn** [bytedance/danmu.js#2]
只发一条弹幕666。  这条弹幕从视频右侧飘到左侧后会在重复从右侧飘到左侧，然后就这样无限循环。 这个是为什么？

**Comment by conanjunn** [comment]
补充下：  如果视频暂停（或者播放完毕），然后发弹幕就会出现我上述的情况，正常播放时发弹幕不会出现

**Comment by uojo** [comment]
live: true
