### ISSUE TITLE
failed to "npm install"

### ISSUE THREAD

**Issue by connLAN** [bytedance/danmu.js#24]
os: fedora, node.js: v18.17.0.1
os: win10 , node.js: v18.17.0

 Accoring to the README.md guide, I ran "npm install" after cloning the repository, but it failed at the same place every time. Can you provide some assistance in resolving this issue? The error message is posted below.

npm install
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to http://bnpm.byted.org/@byted-lint/eslint-plugin-meta/-/eslint-plugin-meta-0.0.20.tgz failed, reason: getaddrinfo ENOTFOUND bnpm.byted.org
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by gemxx** [comment]
@byted-lint/eslint-plugin-meta is removed, pull & have a try
