### ISSUE TITLE
发送弹幕，在style中设置fontSize属性无效

### ISSUE THREAD

**Issue by pluskeen** [bytedance/danmu.js#27]
danmujs.sendComment({
    duration: 15000,
    id: generateUUID(),
    txt: '弹幕内容',
    style: {
      color: '#ff9500',
      fontSize: '200px',
      border: 'solid 1px #ff9500',
      borderRadius: '50px',
      padding: '5px 11px',
      backgroundColor: 'rgba(255, 255, 255, 0.1)'
    }
  })

style中除了fontSize属性不生效，其他都可以。改变fontSize，需要使用setFontSize API才行。

期待回复，谢谢。

**Comment by startjava** [comment]
https://github.com/bytedance/xgplayer/issues/1360
